name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet

        # uses: action @ branch name or tag name or commit ID
        uses: actions/hello-world-javascript-action@v1

        # input
        with:
          # from README.md
          who-to-greet: Selfnote
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}" 