# Workflow名
name: Shell Commands
# イベントトリガー
# Git Pushした時にこのワークフローを実行する
on: [push]

jobs:
  # job name
  run-shell-commmand:
    # VM type
    runs-on: ubuntu-latest
    # job steps
    steps:
      # step1
      - name: echo a string
        # run: echo "Hello World"
        run: echo "Hello World"
      # step2
      - name: multiline script
        run: | # concatenate with pipe when you add other orders
          node -v
          npm -v
      # w/ python
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
      # Windows
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
